name: cru_macros — Build & Publish Release Tarball

on: push

jobs:
  build-tarball:
    name: Build and upload package tarball
    runs-on: ubuntu-latest
    permissions:
      contents: write  # required to upload assets to the release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build gzipped tarball
        # Package git repo into a gzipped tarball for inclusion in release artifacts
        run: |
          cd ..
          tar -czf "cru_macros-${{ github.ref_name }}.tar.gz" dbt_cru_macros/
          mv "cru_macros-${{ github.ref_name }}.tar.gz" dbt_cru_macros/

      - name: Upload tarball to release
        uses: softprops/action-gh-release@v2.6.1
        if: github.ref_type == 'tag'
        with:
          files: "cru_macros-${{ github.ref_name }}.tar.gz"
